### ISSUE TITLE
Custom output filename

### ISSUE THREAD

**Issue by mikeyoon** [brillout/gulp-jspm#19]
Is is possible to specify an output filename for the bundle? This would be helpful for entry points that are not JS files.

**Comment by brillout** [comment]
The solution until now has to been to use `gulp-rename`.

Many people ask for that and we should therefore directly implement that.
Keeping this ticket upon until implemented.

In the mean time use `gulp-rename`

**Comment by Smolations** [comment]
Does it really take 6 months to implement this feature? This issue also affects sourcemapping. You have to rename the files before writing the sourcemaps in order to make sure the sourceMappingUrl matches the newly renamed filename. This feels very hacky. Users of the library should have had full control over the bundle file name from the beginning.

Also, not sure if this hack is the cause, but I am unable to get consistent results using this library compared to using the jspm lib directly. My app is failing to load when bundling with this lib.

**Comment by brillout** [comment]
@Smolations you are right, the implementation should be rather small. Therefore if you really want this then feel free to create a Pull Request. I'll eventually do it myself if no one's up for the task.

As for your consistency issue, check the `verbose` option of gulp-jspm. This will show you exactly how jspm is being called.

**Comment by jansensan** [comment]
@brillout @Smolations Made a PR for this issue: https://github.com/brillout/gulp-jspm/pull/36

**Comment by brillout** [comment]
published as `gulp-jspm@0.5.13`
